---
- name: Create a Persistent Volume Claim (PVC)
  kubernetes.core.k8s:
    state: present
    template: 'psql-pvc'
    wait: yes
  
- name: Deploy Cool DB
  kubernetes.core.k8s:
    state: present
    template: 'psql-deployment'
    wait: yes
    wait_timeout: 300

- name: Deploy Cool DB Service
  kubernetes.core.k8s:
    state: present
    template: 'psql-service'
    wait: yes