---
- name: Deploy Cache DB
  kubernetes.core.k8s:
    state: present
    template: 'redis-deployment'
    wait: yes
    wait_timeout: 300

- name: Deploy Cool DB Service
  kubernetes.core.k8s:
    state: present
    template: 'redis-service'
    wait: yes

