---
- name: Delete a Persistent Volume Claim (PVC)
  kubernetes.core.k8s:
    state: absent
    template: 'psql-pvc'
  when: delete_data is defined and delete_data == 'true'
  
- name: Undeploy Cool DB
  kubernetes.core.k8s:
    state: absent
    template: 'psql-deployment'

- name: Undeploy Cool DB Service
  kubernetes.core.k8s:
    state: absent
    template: 'psql-service'
