---
# Playbook to deploy coolreads and its components

- name: Deploy Coolreads
  hosts: localhost
  gather_facts: false
  roles:
    - gke_namespace_create
    - coolDB_deploy
    - coolCache_deploy
    - coolreads_deploy
    
